### ISSUE TITLE
Support used with cmake find_package

### ISSUE THREAD

**Issue by 5c4lar** [jstaursky/coronium#1]
Thanks for your excellent work! Offering the choice of using CMake as the build system for the user project would make it even better.

**Comment by jstaursky** [comment]
Hey thanks! Are you referring the tests/examples ? I think I have broken example two in the past few commits if your having build issues. I could post what the equivalent cmake build would be for 1 of the examples if that's what you are wanting. But I probably will keep them as simple Makefiles in the repo(for now) just because that means less cmds for me to type while testing.

**Comment by jstaursky** [comment]
Are you wanting a find_package module made?  TBH I don't really understand the benefit to using find_package over using the cmake built-in find_library.

**Comment by 5c4lar** [comment]
> Are you wanting a find_package module made? TBH I don't really understand the benefit to using find_package over using the cmake built-in find_library.

Thanks for your reply. I wanted to use this library in another CMake project, and I want to find this package by a `find_package`. I've switched to [sleigh](https://github.com/lifting-bits/sleigh) now.

**Comment by jstaursky** [comment]
Good luck with w/ your project!
